version: "3"

services:

## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ##
## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ##
  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --broadcast-rpc-address scylla-node1
    ports:
      - "9042:9042"
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - digital-twin-network

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --broadcast-rpc-address scylla-node2
    ports:
      - "9043:9042"
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - digital-twin-network

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0 --broadcast-rpc-address scylla-node3
    ports:
      - "9044:9042"
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    networks:
      - digital-twin-network
## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ##
## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ## ## ------------- SCYLLA DB ------------- ##

## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ##
## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ##
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.14
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "./mosquitto/dtBroker.conf:/mosquitto/config/mosquitto.conf"
      - "./mosquitto/dtPassword:/mosquitto/config/mosquitto.passwd"
#      - "./mosquitto/data:/mosquitto/data"
#      - "./mosquitto/log:/mosquitto/log"
    networks:
      - digital-twin-network

## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ##
## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ## ## ------------- MOSQUITTO ------------- ##

## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ##
## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ##
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
#    volumes:
#      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw              # Persistence data
    networks:
      - digital-twin-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro                # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - digital-twin-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - digital-twin-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
#      - ./filebeat/data:/usr/share/filebeat/data:rw                        # Persistence data
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash
    networks:
      - digital-twin-network
## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ##
## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ## ## ------------- ELASTIC STACK ------------- ##

## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ##
## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ##

  well-orchestrator:
    container_name: well-orchestrator
    build:
      context: .
      dockerfile: Dockerfile
    image: well-orchestrator:latest
    environment:
      - SCYLLA_NODE1_URL=scylla-node1
      - SCYLLA_NODE2_URL=scylla-node2
      - SCYLLA_NODE3_URL=scylla-node3
    ports:
      - "8082:8082"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    depends_on:
      - scylla-node1
      - scylla-node2
      - scylla-node3
      - mosquitto
    networks:
      - digital-twin-network

  virtual-tubing:
    container_name: virtual-tubing
    image: virtual-tubing:latest
    environment:
      - SCYLLA_NODE1_URL=scylla-node1
      - SCYLLA_NODE2_URL=scylla-node2
      - SCYLLA_NODE3_URL=scylla-node3
    ports:
      - "8085:8085"
    depends_on:
      - scylla-node1
      - scylla-node2
      - scylla-node3
      - mosquitto
    networks:
      - digital-twin-network

  virtual-anm:
    container_name: virtual-anm
    image: virtual-anm:latest
    environment:
      - SCYLLA_NODE1_URL=scylla-node1
      - SCYLLA_NODE2_URL=scylla-node2
      - SCYLLA_NODE3_URL=scylla-node3
    ports:
      - "8084:8084"
    depends_on:
      - scylla-node1
      - scylla-node2
      - scylla-node3
      - mosquitto
    networks:
      - digital-twin-network

  virtual-choke-valve:
    container_name: virtual-choke-valve
    image: virtual-choke-valve:latest
    environment:
      - SCYLLA_NODE1_URL=scylla-node1
      - SCYLLA_NODE2_URL=scylla-node2
      - SCYLLA_NODE3_URL=scylla-node3
    ports:
      - "8081:8081"
    depends_on:
      - scylla-node1
      - scylla-node2
      - scylla-node3
      - mosquitto
    networks:
      - digital-twin-network

  dashboard-service:
    container_name: dashboard-service
    image: dashboard-service:latest
    ports:
      - "8083:8083"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    networks:
      - digital-twin-network

  data-provider:
    container_name: data-provider
    image: data-provider:latest
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto
    networks:
      - digital-twin-network

## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ##
## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ## ## ------------- DIGITAL TWIN ------------- ##

networks:
  digital-twin-network:
    driver: bridge
